/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import { Platform, ScrollView, StyleSheet, Text, View, Button } from 'react-native';
import React, { Component } from 'react';
import { SpotIM, SpotIMAPI, SpotIMEventEmitter } from '@spot.im/react-native-spotim';

export default class App extends Component {
  constructor(props) {
    super(props)

    this.state = {
      postId: "sdk1",
      show: true,
      subsctiption: null
    }

    SpotIMAPI.init("sp_eCIlROSD")
  }

  onTrackAnalyticsEvent(event) {
    console.log('\n', event.type, '\n', event);
  }

  componentDidMount() {
    // SPOT IM INIT


    // Show analytics events
    // SpotIMEventEmitter.addListener('trackAnalyticsEvent', this.onTrackAnalyticsEvent);

    const onStartLoginFlow = (event) => {
      console.log("onStartLoginFlow");
      // Load here login view
    }
    const subscription = SpotIMEventEmitter.addListener('startLoginFlow', onStartLoginFlow);
  }

  render() {
    console.log("render :: postId - " + this.state.postId);

    // COMPLETE SSO FLOW
    // const Http = new XMLHttpRequest();
    // const url=SSO_ENDPOINT_BASE_URL+SSO_ENDPOINT_LOGIN;
    // Http.open("POST", url);
    // Http.setRequestHeader("content-type","application/json");
    // Http.send(JSON.stringify({
    //   "username":USERNAME,
    //   "password":PASSWORD
    // }));
    // Http.onreadystatechange=(e) => {
    //   if(Http.readyState == 4) {
    //     console.log(Http.responseText);
    //     const json = JSON.parse(Http.responseText);
    //     const userToken = json.token
    //     console.log("user token: " + userToken);
    //     SpotIMAPI.startSSO()
    //     .then((data) => {
    //       console.log("SpotIm: Succees for SSO: ");
    //       console.log("SpotIm: Code: " + data.code_a);

    //       const Http = new XMLHttpRequest();
    //       const url=SSO_ENDPOINT_BASE_URL+SSO_ENDPOINT_CODE_B;
    //       Http.open("POST", url);
    //       Http.setRequestHeader("access-token-network", SPOT_ACCESS_TOKEN);
    //       Http.setRequestHeader("content-type","application/json");
    //       Http.send(JSON.stringify({
    //         "code_a":data.code_a,
    //         "access_token":userToken,
    //         "username":USERNAME,
    //         "environment":"production"
    //       }));
    //       Http.onreadystatechange=(e) => {
    //         if(Http.readyState == 4) {
    //           const json = JSON.parse(Http.responseText);
    //           console.log("Got code B: ");
    //           console.log(json)
    //           SpotIMAPI.completeSSO(json.code_b)
    //           .then((response) => {
    //             console.log("SpotIm: " + response.success);
    //           })
    //           .catch((error) => {
    //             console.log("SpotIm: " + error);
    //           })
    //         }
    //       }
    //     })
    //     .catch((error) => {
    //       console.log("SpotIm: Api call error: " + error);
    //     });
    //   }
    // }


    // SSO WITH JWT
    // SpotIMAPI.sso(JWT_TOKEN)
    // .then((data) => {
    //   console.log("Succees for SSO: ");
    //   console.log(data.success);
    // }).catch((error)=>{
    //   console.log("Api call error: " + error.error);
    // });

    // LOGOUT
    // SpotIMAPI.logout()
    // .then((response) => {
    //   console.log("Logout success: " + response.success);
    // })
    // .catch((error) => {
    //   console.log("Logout error: " + error);
    // });

    // // GET USER STATUS
    // SpotIMAPI.getUserLoginStatus()
    // .then((response) => {
    //   console.log("User status is: " + response.status);
    // })
    // .catch((error) => {
    //   console.log("User status error: ");
    //   console.log(error);
    // });

    return (
      <ScrollView style={styles.container}>
        <View style={{marginTop: 30}} />
        <Text style={styles.welcome}>Spot.IM React-Native Demo App</Text>
        <Text style={{margin:10}}>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</Text>
        <View style={{marginTop: 30}} />
        {this.state.show && (
          <SpotIM
            postId={this.state.postId}
            url="http://www.spotim.name/bd-playground/post9.html"
            title="Spot.IM is aiming for the stars!"
            subtitle=""
            thumbnailUrl="https://images.spot.im/v1/production/trqsvhyviejd0bfp2qlp"
            showLoginScreenOnRootScreen={false}
            style={{flex: 1}} />
        )}
        <Button title="Change Post ID" onPress={() => {
            this.setState({postId: this.state.postId === "sdk1" ? "sdk2" : "sdk1"})
        }}/>
      <Button title="Hide / Show" onPress={() => {
            this.setState({show: !this.state.show})
        }}/>
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginVertical: 30,
  },
  welcome: {
    fontSize: 24,
    color: 'blue',
    textAlign: 'center',
    marginTop: 40,
    marginBottom: 20,
  },
});
