/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import { Platform, ScrollView, StyleSheet, Text, View, Button } from 'react-native';
import React, { Component } from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import 'react-native-gesture-handler';
import { SpotIM, SpotIMAPI, SpotIMEventEmitter } from '@spot.im/react-native-spotim';
import MainScreen from './Screens/MainScreen.js'
import ArticlesScreen from './Screens/ArticlesScreen.js'
import ArticleScreen from './Screens/ArticleScreen.js'
import LoginScreen from './Screens/LoginScreen.js'

const Stack = createStackNavigator();
export default class App extends Component {
  constructor(props) {
    super(props)

    this.state = {
      postId: "sdk1",
      show: true,
      subsctiption: null
    }
  }

  onTrackAnalyticsEvent(event) {
    console.log('\n', event.type, '\n', event);
  }

  componentDidMount() {
    // SPOT IM INIT


    // Show analytics events
    // SpotIMEventEmitter.addListener('trackAnalyticsEvent', this.onTrackAnalyticsEvent);

    // const onStartLoginFlow = (event) => {
    //   console.log("onStartLoginFlow");
    //   // Load here login view
    //   this.props.navigation.navigate('Login')
    //
    // }
    // const subscription = SpotIMEventEmitter.addListener('startLoginFlow', onStartLoginFlow);
  }

  render() {
    console.log("render :: postId - " + this.state.postId);

    //
    // return (
    //   <ScrollView style={styles.container}>
    //     <View style={{marginTop: 30}} />
    //     <Text style={styles.welcome}>Spot.IM React-Native Demo App</Text>
    //     <Text style={{margin:10}}>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</Text>
    //     <View style={{marginTop: 30}} />
    //     {this.state.show && (
    //       <SpotIM
    //         postId={this.state.postId}
    //         url="http://www.spotim.name/bd-playground/post9.html"
    //         title="Spot.IM is aiming for the stars!"
    //         subtitle=""
    //         thumbnailUrl="https://images.spot.im/v1/production/trqsvhyviejd0bfp2qlp"
    //         showLoginScreenOnRootViewController={false}
    //         style={{flex: 1}} />
    //     )}
    //     <Button title="Change Post ID" onPress={() => {
    //         this.setState({postId: this.state.postId === "sdk1" ? "sdk2" : "sdk1"})
    //     }}/>
    //   <Button title="Hide / Show" onPress={() => {
    //         this.setState({show: !this.state.show})
    //     }}/>
    //   </ScrollView>
    // );

    return (
      <NavigationContainer>
        <Stack.Navigator initialRouteName="Home">
          <Stack.Screen name="Home"component={MainScreen}/>
          <Stack.Screen name="Articles" component={ArticlesScreen} />
          <Stack.Screen name="Article" component={ArticleScreen} />
          <Stack.Screen name="Login" component={LoginScreen} />
        </Stack.Navigator>
      </NavigationContainer>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginVertical: 30,
  },
  welcome: {
    fontSize: 24,
    color: 'blue',
    textAlign: 'center',
    marginTop: 40,
    marginBottom: 20,
  },
});
